### ISSUE TITLE
Link is not deleted when connected node is deleted

### ISSUE THREAD

**Issue by SadE54** [thedmd/imgui-node-editor#132] opened 2021-10-04 15:07 UTC
Hi 

I'm using the last develop branch and I can see that if i'm deleting a connected node , the link is not deleted and still exist in memory. It cannot be dwran anymore but you can see that the ports are still connected:

![MEFlow_qAALNJvyva](https://user-images.githubusercontent.com/2878768/135876166-5c3315c4-7025-40f1-a3b0-46ca8eabc72a.png)
![MEFlow_3sk5fTfllB](https://user-images.githubusercontent.com/2878768/135876175-bc73eac0-3966-448d-b2b6-a7d9cb6c2eae.png)

**Comment by SadE54** [comment] 2021-10-04 17:21
I find a way to delete link when deleting from context menus
```cplus
if (ImGui::MenuItem("Delete"))
                    {
                        ed::BreakLinks(contextNodeId);
                        ed::DeleteNode(contextNodeId);
                    }
```
But I'm still unable to get it deleted if I delete the node using the delete key. The system seems to be different and deeply embedded in node editor internals 🤔

**Comment by ToppDev** [comment] 2021-10-05 11:04
Hey, your problem is easy solvable. You just need to manually remove the links from the list. I made a Pull Request where this is shown #133

**Comment by thedmd** [comment] 2021-11-18 08:50
In blueprint example there is a bug. There is a easy workaround. Basically first run node `QueryDeletedNode`, this will queue all connected link to be deleted and `QueryDeletedLink` will return them too.

Does this help?

**Comment by SadE54** [comment] 2021-11-18 08:59
Thanks ! I found a temporary solution , but I will try asap your fix

**Comment by thedmd** [comment] 2021-11-18 09:26
My choice of API make it easy to make this mistake. Sorry for that.

**Comment by SadE54** [comment] 2021-11-18 09:29
No problem, I'm already so happy to use such a nice  tool ! :)

**Comment by thedmd** [comment] 2022-11-02 07:07
Duplicate of #182, fixed on `develop`.

**Closed by thedmd** 2022-11-02 07:07 UTC
