### ISSUE TITLE
Disable mouse interaction

### ISSUE THREAD

**Issue by Namek** [thedmd/imgui-node-editor#172] opened 2022-07-22 16:50 UTC
Ho, I would like to disable mouse interaction when custom mouse interaction happens. In the example below I want to drag item out of the list:

![imgui-node-editor-custom-drag](https://user-images.githubusercontent.com/31058/180486364-4341def6-393b-4919-9b9a-0a49d30bbc7a.gif)

Node selection should be turned off. Any ideas? Even if I had to modify the library?

**Comment by MultiPain** [comment] 2022-07-23 04:05
It does not really solves the problem, but you can rebind mouse buttons:
```cpp
NodeEditor::Config cfg;
cfg.DragButtonIndex = 0;
cfg.SelectButtonIndex = 1;
cfg.NavigateButtonIndex = 2;
cfg.ContextMenuButtonIndex = 1;
NodeEditor::EditorContext* ctx = NodeEditor::CreateEditor(&cfg);
```

**Comment by thedmd** [comment] 2022-08-12 21:13
@Namek  Do I understand correctly that the problem is selection rectangle appearing here?

**Comment by Namek** [comment] 2022-08-13 09:22
@thedmd yes as for now I used the suggestion above but it's not ideal

**Comment by thedmd** [comment] 2022-08-21 15:13
Can you by any chance provide a code sample I can play with to reproduce the issue?

**Comment by MultiPain** [comment] 2022-08-24 06:36
@thedmd fun fact, this issue persist only in [develop](/thedmd/imgui-node-editor/tree/develop) branch, no problems in master.
> Can you by any chance provide a code sample I can play with to reproduce the issue?
There is nothing special 😃 
```cpp
void NodesDemo::Draw()
{
	static float number = 0.0f;
	unsigned int id = 0;
	
	NodeEditor::Begin("MyEditor");
	
	NodeEditor::BeginNode(id++);
	ImGui::Text("Test node");

	ImGui::PushItemWidth(64.0f);
	ImGui::DragFloat("test", &number);
	ImGui::PopItemWidth();

	NodeEditor::EndNode();

	NodeEditor::End();
}
```

**Comment by MultiPain** [comment] 2022-08-24 06:44
Actually, there is something wrong with d&d in master...
![nodes](https://user-images.githubusercontent.com/32590972/186349148-712b8e9a-7bb8-4436-8a5d-4bae5222d0e6.gif)

**Comment by thedmd** [comment] 2022-08-25 03:42
I pushed a fix. Can you confirm if it work for you d&d case too?

**Closed by thedmd** 2022-08-25 03:42 UTC
Labels: bug

**Comment by MultiPain** [comment] 2022-08-25 07:04
@thedmd work fine for me 👍
