### ISSUE TITLE
Document recreating the "Blueprint example" imgui dependency

### ISSUE THREAD

**Issue by crolando** [thedmd/imgui-node-editor#60] opened 2020-04-17 00:46 UTC
In the Readme, there is a section in this location:
_Dependencies > Examples dependencies > https://github.com/thedmd/imgui/tree/feature/layout (used in blueprints sample only)_

I am finding that the "copy of imgui that the blueprint example depends on" is hard to track down or re-create on my own.  Let me explain what I've found:
- The "layout" branch you talk about is insufficient to compile the blueprint example with, because the blueprint example also needs the "draw list fringe scale" feature.
- The "Combined" branch, which has the layout and fringe scale features together works pretty darn good, but has a bug...

The bug (using your combined branch as the blueprint imgui dependency) is that the background grid line thickness and icon thickness don't scale correctly when you zoom in or out.  

With my project, I wanted to do some things using the Blueprint example as a base.  I can use the IMGui copy you provide in the third-party directory, but this introduces a dependency on you keeping it updated, which makes me a little nervous.  I would rather be able to make the dependency myself using a patching system if possible.  

So for this bug resolution, I would like the readme to be updated with some instructions on creating the blueprint example imgui version that you have provided, or to let me know if "I've got it all wrong".  Thanks!

**Comment by thedmd** [comment] 2020-04-17 16:44
Hello,

About state of layouts. Support for stack layout is baking as PR for some time (see: <https://github.com/ocornut/imgui/pull/846>). I hope when time comes Omar will decide it's fate. As for now I maintaining it by keeping it up to date.

You're right about fringe scale I will push a patch to that.
It still does not compile because `ImGuiKey_F` is missing. This is a matter of commenting single line in backed code. By the way adding extra keys is also a PR for ImGui. I will try to gen an update on that.

Can you post a picture of grid not scaling right and tell more what is an expected behavior?

You pretty much got it right. My goal was to enable editor on vanilla copy of ImGui which is done, examples proved itself to be more challenging, hence layout branch dependency.

As a draft for instruction:
```batch
git clone https://github.com/ocornut/imgui.git
cd imgui
git remote add thedmd git@github.com:thedmd/imgui.git
git remote update
git checkout -b for_blueprints origin/master
git merge thedmd/feature/layout
git merge thedmd/feature/extra-keys
git merge thedmd/feature/draw-list-fringe-scale
```

**Comment by crolando** [comment] 2020-04-17 17:57
Thanks for the help.

Here is a gif that has two frames.  one frame shows line thicknesses that are correct when zoomed in. This one is built against your internal imgui version.   The second frame shows very thin lines when zoomed in.  This is built against your "combined" imgui branch.

![stroke_thickness](https://user-images.githubusercontent.com/1946494/79598015-3e3d6880-80b1-11ea-8089-997c6565cb1a.gif)

I tried to debug this but ran out of time yesterday.  I think this is one of those things where your knowledge could help speed up my debugging greatly since you wrote the system.  When the vertexes for those lines get added to the drawlists, they seem to have a normal thickness at that point.  I asked for help when I started looking at your CanvasView object.  To my quick study, it looks like the imgui draw list stuff gets "zoomed" (scaled) when you call LeaveLocal() on the CanvasView.  The canvas runs through the drawlist and applies scale/zoom & pan transformations to the vertexes and re-saves them to the draw list.  I am wondering if maybe the lines are in a different "channel" or "layer" because they are somehow being missed.. but also not being missed.  I'm not sure why it wouldn't work with the **thickness** part of the line, but works with the line **extents**.  Maybe the thickness is somehow zero due to variable width truncation?  I may very well be looking in the wrong spot and this could all be a red herring.   Thanks for the help!

**Comment by thedmd** [comment] 2020-04-17 18:22
I pushed changes so you can now build blueprints with layout branch only.

Thin lines most likely mean fringe scale was not merged into combined branch. I will update ImGui soon. At the moment I'm waiting for another bugfix to be merged into ImGui, before I update combined branch. In the matter of fact I will run exact script I posted above.

Please note, if you use copy of ImGui without fringe scale you will see thin lines.

**Comment by crolando** [comment] 2020-04-17 21:22
The submission in `2522c65` has resolved the inaccuracy in the readme by making the code hold true to the readme. This issue is resolved as far as I'm concerned.  

Thank you, this compiles well.  To follow up on the result: the lines are blurry rather than thin.  This is a good state for my purposes; I will just limit the zoom range so users can't get so close.  

![sans_fringe_scale](https://user-images.githubusercontent.com/1946494/79614242-245e4e80-80ce-11ea-9fe0-6c4cd5ba4d6d.jpg)

**Comment by thedmd** [comment] 2020-04-17 22:06
Great you have it working.

Thin lines may be a result of me resolving conflict in a wrong way while preparing combined branch. That will be fixed.

Blurry lines is an actual effect of lack of fringe scale, now fringe has constant 1px size and if you zoom in fringe is getting wider which result in blurry output. Hopefully HiDPI work on ImGui resolve this problem some day.

**Closed by thedmd** 2020-04-17 22:06 UTC
